# Generated by Django 6.0.2 on 2026-02-24 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('organizer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('organization_type', models.CharField(max_length=50, null=True)),
                ('verified_status', models.CharField(max_length=20, null=True)),
                ('created_at', models.DateField(null=True)),
                ('update_at', models.DateField(null=True)),
            ],
            options={
                'db_table': 'organizer',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateField(null=True)),
                ('update_at', models.DateField(null=True)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('start_date', models.DateField(null=True)),
                ('registration_link', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('created_at', models.DateField(null=True)),
                ('updated_at', models.DateField(null=True)),
                ('organizer', models.ForeignKey(db_column='organizer_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='studentlink.organizer')),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('registration_id', models.IntegerField(primary_key=True, serialize=False)),
                ('registration_date', models.DateField(null=True)),
                ('created_at', models.DateField(null=True)),
                ('updated_at', models.DateField(null=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('event', models.ForeignKey(db_column='event_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='studentlink.event')),
                ('student', models.ForeignKey(db_column='student_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='studentlink.student')),
            ],
            options={
                'db_table': 'registration',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.IntegerField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(null=True)),
                ('comments', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateField(null=True)),
                ('updated_at', models.DateField(null=True)),
                ('event', models.ForeignKey(db_column='event_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='studentlink.event')),
                ('student', models.ForeignKey(db_column='student_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='studentlink.student')),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
    ]
