# Generated by Django 6.0.2 on 2026-04-03 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentlink', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='organizer',
        ),
        migrations.RemoveField(
            model_name='event',
            name='registration_link',
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(default='General', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(default='Upcoming', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(default='Untitled Event', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='comments',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='event',
            field=models.ForeignKey(db_column='event_id', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='studentlink.event'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='student',
            field=models.ForeignKey(db_column='student_id', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='studentlink.student'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='email',
            field=models.CharField(default='unknown@example.com', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='name',
            field=models.CharField(default='Unknown Organizer', max_length=100),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='organization_type',
            field=models.CharField(default='General', max_length=50),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='password',
            field=models.CharField(default='password', max_length=100),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='phone',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='update_at',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='verified_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='registration',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='registration',
            name='event',
            field=models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='studentlink.event'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='registration_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='registration',
            name='student',
            field=models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='studentlink.student'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='updated_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='update_at',
            field=models.DateField(),
        ),
    ]
