# Generated by Django 6.0.2 on 2026-04-04 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentlink', '0002_remove_event_organizer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='roll_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='registration',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='registration_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='registration_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(default='Registered', max_length=20),
        ),
        migrations.AlterField(
            model_name='registration',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='city',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default='Student', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='update_at',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('student', 'event')},
        ),
    ]
