# Generated by Django 6.0.2 on 2026-04-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentlink', '0003_student_roll_number_alter_registration_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
