# Generated by Django 6.0.2 on 2026-04-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentlink', '0004_alter_feedback_feedback_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
    ]
